[project]
site_name = "Notes"
site_description = "Beyond欣 's Notes"
site_author = "Beyond欣"
site_url = "https://notes.beyondxin.top/"
copyright = """
<a href="https://beian.miit.gov.cn/" target="_blank">京ICP备2023033867号</a>
"""
use_directory_urls = false
extra_css = ["css/extra.css"]


nav = [
    { "Qt" = [
        { "自定义控件" = [
            "Qt/自定义控件/QGraphics文字视频.md",
            "Qt/自定义控件/边界修正控件.md",
            "Qt/自定义控件/绘制牛眼图.md",
            "Qt/自定义控件/伪彩图.md",
            "Qt/自定义控件/图片对比选择浏览器.md",
            "Qt/自定义控件/多边形选择.md",
            "Qt/自定义控件/双滑块.md",
            "Qt/自定义控件/渐变消失.md",
            "Qt/自定义控件/自定义菜单栏快捷方式.md",
            "Qt/自定义控件/任意拖拽窗口.md",
            "Qt/自定义控件/显示cpu和内存信息.md",
            "Qt/自定义控件/多图选择目标点Demo.md",
            "Qt/自定义控件/文件监听线程.md",
            "Qt/自定义控件/FTP工具.md",
            "Qt/自定义控件/GithubImageHost.md",
        ] },
        { "使用技巧" = [
            "Qt/使用技巧/Markdown转world.md",
            "Qt/使用技巧/百度智能云API鉴权.md",
            "Qt/使用技巧/Json操作封装.md",
            "Qt/使用技巧/QProxyStyle.md",
            "Qt/使用技巧/Qt程序单元测试.md",
            "Qt/使用技巧/利用Qt实现Https网络请求.md",
            "Qt/使用技巧/文件相关操作.md",
            "Qt/使用技巧/更改程序当前目录.md",
            "Qt/使用技巧/控件隐藏实现方式.md",
            "Qt/使用技巧/样式表.md",
            "Qt/使用技巧/字符串操作.md",
            "Qt/使用技巧/简单封包拆包协议.md",
            "Qt/使用技巧/生成pdf.md",
            "Qt/使用技巧/简单动画封装.md",
            "Qt/使用技巧/网络相关整理.md",
            "Qt/使用技巧/自定义结构体实现本地缓存.md",
            "Qt/使用技巧/设置程序级别属性.md",
            "Qt/使用技巧/设置开机自启.md",
            "Qt/使用技巧/读写配置文件封装.md",
            "Qt/使用技巧/解析命令行.md",
            "Qt/使用技巧/语言切换QTranslator.md",
            "Qt/使用技巧/帮助文档QTAssistant.md",
            "Qt/使用技巧/QuaZip.md",
            "Qt/使用技巧/SQLite.md",
            "Qt/使用技巧/共享内存.md",
            "Qt/使用技巧/任意拖动曲线.md",
            "Qt/使用技巧/QPainter绘制文字换行.md",
            "Qt/使用技巧/防止主线程阻塞.md",
            "Qt/使用技巧/识别外部存储设备.md",
            "Qt/使用技巧/IPC进程间通讯.md",
            "Qt/使用技巧/线程使用心得.md",
        ] },
        { "自带控件" = [
            "Qt/自带控件/QDialog.md",
            "Qt/自带控件/QComboBox.md",
            "Qt/自带控件/QLabel.md",
            "Qt/自带控件/QLineEdit.md",
            "Qt/自带控件/QPlainTextEdit.md",
            "Qt/自带控件/QScrollAreaqt.md",
            "Qt/自带控件/QGraphicsScene.md",
            "Qt/自带控件/QTextedit.md",
            "Qt/自带控件/QWidget.md",
            "Qt/自带控件/QTreeWidget-View.md",
        ] },
        { "项目配置" = [
            "Qt/项目配置/QT指定的字体不存在.md",
            "Qt/项目配置/判断当前系统.md",
            "Qt/项目配置/QT预编译加快速度.md",
            "Qt/项目配置/编译报错排查.md",
            "Qt/项目配置/安装Qt开发环境.md",
            "Qt/项目配置/QT配置WebAssembly.md",
        ] },
        { "QtCreator" = [
            "Qt/QtCreator/QtCreator格式化代码.md",
            "Qt/QtCreator/Linux无法输入中文.md",
            "Qt/QtCreator/qss支持语法高亮.md",
            "Qt/QtCreator/QtCreator设置.md",
            "Qt/QtCreator/python IDE.md",
            "Qt/QtCreator/Kit配置.md",
        ] },
        { "源码学习" = [
            "Qt/源码学习/QObject.md",
            "Qt/源码学习/元对象系统.md",
            "Qt/源码学习/Q_PROPERTY.md",
            "Qt/源码学习/QFileSystemModel.md",
            "Qt/源码学习/QStringListModel.md",
            "Qt/源码学习/Qt析构机制.md",
        ] },
        { "图像操作" = [
            "Qt/图像操作/QImage转cvMat.md",
            "Qt/图像操作/缩放图片.md",
            "Qt/图像操作/图像叠加、二值、删除背景.md",
            "Qt/图像操作/剔除背景并找重心.md",
            "Qt/图像操作/利用Qt实现Gif转预览图片.md",
        ] },
        { "音视频" = [
            "Qt/音视频/QT6音频可视化.md",
        ] },
        { "QML" = [
            "Qt/QML/Hello QML.md",
            "Qt/QML/3D模型预览.md",
            "Qt/QML/视频播放器.md",
            "Qt/QML/打包.md",
        ] },
    ] },
    { "Vtk" = [
        { "交互" = [
            "Vtk/交互/屏幕坐标转世界坐标.md",
            "Vtk/交互/多Actor单独交互.md",
            "Vtk/交互/多Actor绑定选中事件.md",
            "Vtk/交互/交互.md",
        ] },
        { "使用技巧" = [
            "Vtk/使用技巧/编译VTK.md",
            "Vtk/使用技巧/MPR每张图对应空间位置提示.md",
            "Vtk/使用技巧/调试时随时浏览模型、图像.md",
            "Vtk/使用技巧/设置颜色缓冲.md",
            "Vtk/使用技巧/绘制螺钉螺纹线.md",
            "Vtk/使用技巧/vtk各渲染窗口区别.md",
            "Vtk/使用技巧/使用中文图例、标签.md",
            "Vtk/使用技巧/vtk图片显示.md",
            "Vtk/使用技巧/多线程框架vtkMultiThreader.md",
            "Vtk/使用技巧/适配触摸屏.md",
            "Vtk/使用技巧/切换相机标准视角.md",
            "Vtk/使用技巧/模型cell不同颜色.md",
            "Vtk/使用技巧/无法移动手柄.md",
        ] },
        { "类型转换" = [
            "Vtk/类型转换/三维模型转为二维切片.md",
            "Vtk/类型转换/Dcm批量转png.md",
            "Vtk/类型转换/vti转cvMat.md",
            "Vtk/类型转换/dcm转vit.md",
            "Vtk/类型转换/vtp转vtu.md",
            "Vtk/类型转换/vtk转vtp.md",
        ] },
        { "Filter" = [
            "Vtk/Filter/拉普拉斯平滑.md",
            "Vtk/Filter/沿中心线切割管状模型.md",
            "Vtk/Filter/平滑点云.md",
            "Vtk/Filter/求模型间距离.md",
            "Vtk/Filter/计算图形中心线.md",
            "Vtk/Filter/提取连通域.md",
        ] },
        { "重建" = [
            "Vtk/重建/显示cpr序列.md",
            "Vtk/重建/MPR.md",
            "Vtk/重建/CPR.md",
            "Vtk/重建/三维重建.md",
        ] },
        { "体渲染" = [
            "Vtk/体渲染/体绘制.md",
            "Vtk/体渲染/体渲染绘制地球.md",
            "Vtk/体渲染/体绘制剪裁.md",
        ] },
        { "Widget" = [
            "Vtk/Widget/VTK嵌入QT浏览模型.md",
            "Vtk/Widget/可拖动坐标轴.md",
            "Vtk/Widget/vtkWidget.md",
            "Vtk/Widget/vtkWidget屏蔽默认交互.md",
            "Vtk/Widget/vtkBorderWidget.md",
            "Vtk/Widget/vtkTextWidget.md",
            "Vtk/Widget/vtkSeedWidget.md",
            "Vtk/Widget/vtkBrokenLineWidget.md",
            "Vtk/Widget/vtkBoxWidget.md",
            "Vtk/Widget/装配体Assembly.md",
            "Vtk/Widget/vtkRubberBand.md",
            "Vtk/Widget/vtkwidget剪裁.md",
        ] },
    ] },
    { "C++" = [
        { "VisualStudio配置" = [
            "C++/VisualStudio配置/VS与CUDA集成.md",
            "C++/VisualStudio配置/GithubCopilot无提示.md",
            "C++/VisualStudio配置/文本编辑器设置.md",
            "C++/VisualStudio配置/隐藏不必要代码提示.md",
            "C++/VisualStudio配置/集成uncrustify.md",
            "C++/VisualStudio配置/插件.md",
            "C++/VisualStudio配置/VS2026.md",
        ] },
        { "开源库" = [
            { "CMake" = [
                "C++/开源库/CMake/CMake常用指令.md",
                "C++/开源库/CMake/同时编译静态库和动态库.md",
                "C++/开源库/CMake/多个工程共享变量.md",
                "C++/开源库/CMake/批量生成可执行程序.md",
                "C++/开源库/CMake/根据不同参数编译不同程序.md",
                "C++/开源库/CMake/版本管理.md",
                "C++/开源库/CMake/组织项目列表.md",
                "C++/开源库/CMake/编译生成第三方库.md",
                "C++/开源库/CMake/设置可执行程序类型.md",
                "C++/开源库/CMake/错误排查.md",
            ] },
            { "DCMTK" = [
                "C++/开源库/DCMTK/DCM标签可视化.md",
                "C++/开源库/DCMTK/PACS.md",
                "C++/开源库/DCMTK/修改UID.md",
                "C++/开源库/DCMTK/dcm转图片.md",
                "C++/开源库/DCMTK/控制台信息过多.md",
                "C++/开源库/DCMTK/编译安装.md",
            ] },
            { "CGAL" = [
                "C++/开源库/CGAL/OFF转STL.md",
                "C++/开源库/CGAL/编译安装.md",
                "C++/开源库/CGAL/提取中心线.md",
                "C++/开源库/CGAL/自相交检测.md",
                "C++/开源库/CGAL/表面细化.md",
                "C++/开源库/CGAL/补洞.md",
            ] },
            { "ITK" = [
                "C++/开源库/ITK/操作dcm标签.md",
                "C++/开源库/ITK/多张图转mha.md",
                "C++/开源库/ITK/最短路径提取.md",
            ] },
            { "LibTorch" = [
                "C++/开源库/LibTorch/模型推理.md",
            ] },
            { "OpenCV" = [
                "C++/开源库/OpenCV/Mat转QImage.md",
                "C++/开源库/OpenCV/提取连通域.md",
                "C++/开源库/OpenCV/通道分离、合并.md",
                "C++/开源库/OpenCV/错误排查.md",
                "C++/开源库/OpenCV/求线段切线和垂线.md",
            ] },
            { "MITK" = [
                "C++/开源库/MITK/MITK交互.md",
                "C++/开源库/MITK/解决CTK和BlueBerry链接问题.md",
            ] },
            "C++/开源库/FFmpeg.md",
            "C++/开源库/Halcon.md",
            "C++/开源库/RCF.md",
        ] },
        { "面试" = [
            { "C++关键字" = [
                "C++/面试/C++关键字/const.md",
                "C++/面试/C++关键字/explict.md",
                "C++/面试/C++关键字/inline.md",
                "C++/面试/C++关键字/staitc.md",
                "C++/面试/C++关键字/new和malloc.md",
                "C++/面试/C++关键字/template using typedef.md",
            ] },
            { "C++语法规则" = [
                "C++/面试/C++语法规则/vector越界引发的bug.md",
                "C++/面试/C++语法规则/动态库、静态库、符号隐藏.md",
                "C++/面试/C++语法规则/回调函数.md",
                "C++/面试/C++语法规则/多态、析构、虚函数.md",
                "C++/面试/C++语法规则/指针值传递与引用传递的比较.md",
                "C++/面试/C++语法规则/指针和引用.md",
                "C++/面试/C++语法规则/模板函数.md",
                "C++/面试/C++语法规则/构造函数和初始化列表.md",
            ] },
            { "数据结构与算法" = [
                "C++/面试/数据结构与算法/Qt数据结构实现.md",
                "C++/面试/数据结构与算法/解决哈希冲突的办法.md",
            ] },
        ] },
    ] },
    { "编程" = [
        { "Git" = [
            "编程/Git/提交.md",
            "编程/Git/常用命令.md",
            "编程/Git/Svn迁移Git.md",
            "编程/Git/中文路径异常.md",
            "编程/Git/批量替换作者.md",
            "编程/Git/管理跟踪文件.md",
            "编程/Git/绑定ssh.md",
            "编程/Git/配置Hooks.md",
            "编程/Git/TortoiseGit使用openssh.md",
        ] },
        { "Go" = [
            "编程/Go/基本语法.md",
            "编程/Go/开发环境部署.md",
            "编程/Go/微信公众号开发.md",
            "编程/Go/GoRoutines.md",
        ] },
        { "前端" = [
            "编程/前端/Node项目配置.md",
            "编程/前端/Vue项目设置.md",
        ] },
        { "Godot" = [
            "编程/Godot/Aseprite编译.md",
            "编程/Godot/Godot编译.md",
            "编程/Godot/GDScript语法.md",
        ] },
        { "MarkDown" = [
            "编程/MarkDown/图片排版.md",
            "编程/MarkDown/列表.md",
        ] },
        { "软件工程" = [
            "编程/软件工程/GitHubActions.md",
        ] },
        { "IDE" = [
            "编程/IDE/VSC远程链接使用copilot.md",
            "编程/IDE/Cmake配置(VSC).md",
            "编程/IDE/IDE.md",
        ] },
        { "视觉优化" = [
            "编程/视觉优化/字体图标的使用.md",
        ] },
    ] },
    { "数据结构与算法" = [
        { "数据结构" = [
            "数据结构与算法/数据结构/0-数据结构.md",
            "数据结构与算法/数据结构/1-数组与链表.md",
            "数据结构与算法/数据结构/2-栈与队列.md",
            "数据结构与算法/数据结构/3-哈希表.md",
            "数据结构与算法/数据结构/4-树.md",
            "数据结构与算法/数据结构/5-堆.md",
            "数据结构与算法/数据结构/6-图.md",
        ] },
        { "算法" = [
            { "搜索" = [
                "数据结构与算法/算法/搜索/搜索.md",
            ] },
            { "排序" = [
                "数据结构与算法/算法/排序/气泡排序.md",
                "数据结构与算法/算法/排序/排序.md",
            ] },
            { "贪心" = [
                "数据结构与算法/算法/贪心/Dijkstra最短路径.md",
            ] },
        ] },
        { "图形几何" = [
            "数据结构与算法/图形几何/四元数和变换矩阵转换.md",
            "数据结构与算法/图形几何/球心拟合.md",
            "数据结构与算法/图形几何/解方程组.md",
        ] },
        "数据结构与算法/文章收藏.md",
    ] },
    { "运维" = [
        "运维/部署Zensical.md",
        "运维/部署v2ray.md",
        "运维/部署七牛云+PicGo图床.md",
        "运维/部署MKDocs.md",
        "运维/阿里云服务器迁移.md",
        "运维/Win跨局域网远程链接.md",
        "运维/部署Gitea.md",
        "运维/部署Docsify.md",
        "运维/Nginx配置.md",
        "运维/Linux建站.md",
        "运维/Windos建站.md",
    ] },
    { "系统" = [
        { "Linux" = [
            "系统/Linux/AppImage压缩与解压.md",
            "系统/Linux/Rdesktop远程连接.md",
            "系统/Linux/VirtualBox启动错误.md",
            "系统/Linux/SSH链接.md",
            "系统/Linux/使用SCP进行文件传输.md",
            "系统/Linux/切换默认Shell.md",
            "系统/Linux/命令行后台运行程序.md",
            "系统/Linux/截图设置.md",
            "系统/Linux/增加swap交换空间.md",
            "系统/Linux/调整缓存压力设置.md",
            "系统/Linux/网站完整下载到本地.md",
        ] },
        { "软件设置" = [
            "系统/软件设置/IDE快捷键.md",
            "系统/软件设置/Windos装机.md",
            "系统/软件设置/Obsidian.md",
            "系统/软件设置/软件设置.md",
            "系统/软件设置/浏览器插件.md",
        ] },
    ] },
    { "我的项目" = [
        "我的项目/AI.xyz.md",
        "我的项目/NixVis.md",
        "我的项目/文字动效助手.md",
        "我的项目/KISSDicomViewer.md",
        "我的项目/禅.md",
        "我的项目/RepoReporter.md",
        "我的项目/YiHangPavilion.md",
        "我的项目/SonicRhythm.md",
    ] },
]


[project.theme]

custom_dir = "overrides"
favicon = "assets/images/favicon.ico"
language = "zh"

features = [
    "announce.dismiss",

    # "content.action.edit",
    # "content.action.view",
    "content.code.annotate",
    "content.code.copy",
    "content.code.select",
    "content.footnote.tooltips",
    "content.tabs.link",
    "content.tooltips",

    "navigation.tabs",
    "navigation.tabs.sticky",
    "navigation.expand",
    "navigation.footer",
    "navigation.indexes",
    "navigation.instant",
    "navigation.instant.prefetch",
    "navigation.instant.progress",
    "navigation.prune",
    "navigation.top",
    "navigation.tracking",
    # "navigation.sections",
    # "navigation.path",

    # "header.autohide",

    "search.highlight",

    "toc.follow",
    # "toc.integrate",
]


[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"


[project.extra]
generator = false
# homepage = "https://www.beyondxin.top"

[[project.extra.social]]
icon = "fontawesome/brands/edge"
link = "https://www.beyondxin.top/"
[[project.extra.social]]
icon = "fontawesome/brands/bilibili"
link = "https://space.bilibili.com/285016963"
